version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - craiga
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: faraday
    versions:
    - 1.3.0
    - 1.3.1
    - 1.4.0
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: activesupport
    versions:
    - 6.0.3.4
    - 6.0.3.5
  - dependency-name: minitest
    versions:
    - 5.14.3
  - dependency-name: octokit
    versions:
    - 4.20.0
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - craiga
  allow:
  - dependency-type: direct
  - dependency-type: indirect
