language: ruby
addons:
  apt:
    packages:
      - aspell
      - aspell-en
script:
  - bundle exec jekyll doctor
  - shellcheck *.sh
  - ./spellcheck.sh
notifications:
  email:
    on_success: change
    on_failure: always
